/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-09-17 11:32:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.oreilly.servlet.MultipartRequest;
import java.util.Enumeration;
import testcsv.CsvAnalysis;
import testjdbc.DbBean;
import java.util.List;

public final class upload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
    String saveDirectory = "C:\\test\\"; 
    // 限制上傳之檔案大小為 5 MB 
    int maxPostSize = 5 * 1024 * 1024 ; 
    MultipartRequest multi = new MultipartRequest(request , 
                       saveDirectory , maxPostSize, "UTF-8"); 
   String filenames = multi.getOriginalFileName("File1"); 
   
         //out.println("上傳了檔案" + filenames + "<br>"); 
         
         CsvAnalysis cc = new CsvAnalysis();
         DbBean dd = new DbBean();
         List dataList = cc.csvString(saveDirectory+filenames);
         
         //out.println("value" + dataList + "<br>");
         out.println(dataList);
         //[[2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420], 
          //[5.59, 5.61, 5.58, 5.6, 5.63, 5.6, 5.62, 5.62, 5.73, 5.69, 5.66, 5.69, 5.68, 5.71, 5.69, 5.68, 5.66, 5.67, 5.66]]
 		for(int i=0;i<dataList.size();i++){
 			System.out.println(dataList.get(i).toString());
 			
 			List insertList  = (List)dataList.get(i);
 			 out.println(insertList);
 			int result = dd.InsertData("insert into CalValue(Frequency,Loss) values (?,?) ", insertList);
 			 out.println(result);
// 			int jj=0;
// 			jj=dataList.size();
// 			out.println("i : " + jj + "<br>"); 
 		}
 		
   

      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
